### ISSUE TITLE
npm `w` package.

### ISSUE THREAD

**Issue by MKRhere** [wbhob/w#1]
Hi,

I'd like to use the npm `w` package for my upcoming node project.
It's supposed to be a really small web templating framework. Let me know if you'd be interested in lending me the package name. Thank you so much :)

**Comment by wbhob** [comment]
I'd be happy to give it to you! What is your username?

**Comment by MKRhere** [comment]
Thank you so much :) I'm indebted!
It's `MKRhere` - https://npmjs.com/~mkrhere

**Comment by wbhob** [comment]
I added you as an owner. You can remove me if you want

**Comment by MKRhere** [comment]
Thank you, I'll leave a line in the Readme back to you.

**Comment by wbhob** [comment]
Happy to help! I appreciate it.
